services:
  - type: web
    name: congestion-pricing-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATA_DIR
        value: ./data
      - key: PYTHONPATH
        value: /opt/render/project/src

  - type: web
    name: congestion-pricing-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://congestion-pricing-backend.onrender.com
